### ISSUE TITLE
Installing Tensorflow 1.4 (ShARC)

### ISSUE THREAD

**Issue by twinkarma** [RSE-Sheffield/GPUComputing#10]
From Madina:

I was trying to install TF and Followed the instructions in:
https://github.com/RSE-Sheffield/GPUComputing/blob/master/deeplearning/Tensorflow.rst

But I got this error:
tensorflow-1.4.0-py2-none-any.whl is not a supported wheel on this platform.

The installation commands I used were as follows:

(tensorflow) [ac4mhx@sharc-node002 stuttering]$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.4.0-py2-none-any.whl
(tensorflow) [ac4mhx@sharc-node002 stuttering]$ pip install $TF_BINARY_URL
tensorflow-1.4.0-py2-none-any.whl is not a supported wheel on this platform.

**Comment by twinkarma** [comment]
Tensorflow 1.4 requires cuDNN 6 which is currently under testing (see rcgsheffield/sheffield_hpc#761 )

**Comment by twinkarma** [comment]
The cuDNN v6 library is installed now and should allow installation of tensorflow 1.4. The following are the instructions:

## To Install for Python 3.5 (with GPU)

```
module load libs/cudnn/6.0/binary-cuda-8.0.44
module load apps/python/anaconda3-4.2.0
conda create -n tensorflow python=3.5
source activate tensorflow
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp35-cp35m-linux_x86_64.whl
#You can now run your python tf script
python my_tfscript.py
```
### Every session after

```
module load libs/cudnn/6.0/binary-cuda-8.0.44
module load apps/python/anaconda3-4.2.0
source activate tensorflow
#You can now run your python tf script
python my_tfscript.py
```

## To install for Python 2.7 (with GPU)

```
module load libs/cudnn/6.0/binary-cuda-8.0.44
module load apps/python/anaconda2-4.2.0
conda create -n tensorflow python=2.7
source activate tensorflow
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp27-none-linux_x86_64.whl
#You can now run your python tf script
python my_tfscript.py

```

### Every session after

```
module load libs/cudnn/6.0/binary-cuda-8.0.44
module load apps/python/anaconda2-4.2.0
source activate tensorflow
#You can now run your python tf script
python my_tfscript.py
```

**Comment by madinaHasan** [comment]
Thanks Twin,

I got the following error: (It complains about the space but I have enough space in the Shared folder)

[ac4mhx@sharc-node002 ~]$ module load libs/cudnn/6.0/binary-cuda-8.0.44
[ac4mhx@sharc-node002 ~]$ module load apps/python/anaconda3-4.2.0
Conda uses environments to load different sets of Python packages
type conda env list to see the environments availible.
[ac4mhx@sharc-node002 ~]$ conda create -n tensorflow python=3.5


CondaValueError: Value error: prefix already exists: /home/ac4mhx/.conda/envs/tensorflow


[ac4mhx@sharc-node002 ~]$ source activate tensorflow
(tensorflow) [ac4mhx@sharc-node002 ~]$ pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp35-cp35m-linux_x86_64.whl
Collecting tensorflow-gpu==1.4.0 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp35-cp35m-linux_x86_64.whl
  Downloading https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp35-cp35m-linux_x86_64.whl (170.1MB)
    100% |████████████████████████████████| 170.1MB 7.6kB/s 
Collecting numpy>=1.12.1 (from tensorflow-gpu==1.4.0)
  Downloading numpy-1.13.3-cp35-cp35m-manylinux1_x86_64.whl (16.9MB)
    100% |████████████████████████████████| 16.9MB 71kB/s 
Collecting six>=1.10.0 (from tensorflow-gpu==1.4.0)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting tensorflow-tensorboard<0.5.0,>=0.4.0rc1 (from tensorflow-gpu==1.4.0)
  Downloading tensorflow_tensorboard-0.4.0rc3-py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 565kB/s 
Collecting enum34>=1.1.6 (from tensorflow-gpu==1.4.0)
  Downloading enum34-1.1.6-py3-none-any.whl
Collecting wheel>=0.26 (from tensorflow-gpu==1.4.0)
  Downloading wheel-0.30.0-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 1.4MB/s 
Collecting protobuf>=3.3.0 (from tensorflow-gpu==1.4.0)
  Downloading protobuf-3.5.1-cp35-cp35m-manylinux1_x86_64.whl (6.4MB)
    100% |████████████████████████████████| 6.4MB 212kB/s 
Collecting markdown>=2.6.8 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
  Downloading Markdown-2.6.10.zip (414kB)
    100% |████████████████████████████████| 419kB 4.1MB/s 
Collecting html5lib==0.9999999 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
  Downloading html5lib-0.9999999.tar.gz (889kB)
    100% |████████████████████████████████| 890kB 1.7MB/s 
Collecting werkzeug>=0.11.10 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
  Downloading Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
    100% |████████████████████████████████| 327kB 4.6MB/s 
Collecting bleach==1.5.0 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
  Downloading bleach-1.5.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.3.0->tensorflow-gpu==1.4.0)
  Downloading setuptools-38.2.5-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 3.1MB/s 
Building wheels for collected packages: markdown, html5lib
  Building wheel for markdown failed: [Errno 28] No space left on device: '/home/ac4mhx/.cache/pip/wheels'
  Building wheel for html5lib failed: [Errno 28] No space left on device: '/home/ac4mhx/.cache/pip/wheels'
Failed to build markdown html5lib
Installing collected packages: numpy, six, wheel, markdown, html5lib, werkzeug, bleach, setuptools, protobuf, tensorflow-tensorboard, enum34, tensorflow-gpu
Exception:
Traceback (most recent call last):
  File "/home/ac4mhx/.conda/envs/tensorflow/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/ac4mhx/.conda/envs/tensorflow/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/ac4mhx/.conda/envs/tensorflow/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/ac4mhx/.conda/envs/tensorflow/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/ac4mhx/.conda/envs/tensorflow/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/ac4mhx/.conda/envs/tensorflow/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/ac4mhx/.conda/envs/tensorflow/lib/python3.5/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/ac4mhx/.conda/envs/tensorflow/lib/python3.5/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/home/ac4mhx/.conda/envs/tensorflow/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: '/home/ac4mhx/.conda/envs/tensorflow/lib/python3.5/site-packages/numpy-1.13.3.dist-info'

**Comment by willfurnass** [comment]
It looks like you have exhausted your quota  for `/home/USERNAME` by creating large conda environments.  This is quite common!  You can tell conda to create environments under `/data/USERNAME` instead (where your quota is 10x larger) by adding the following to your `~/.bashrc` file:

```
if [[ -n $SGE_CLUSTER_NAME ]]; then
    export CONDA_ENVS_PATH=/data/$USER/.conda-${SGE_CLUSTER_NAME}
fi
```

You then need to run

`source ~/.bashrc`

once, then you should re-create your conda environment(s).

**Comment by madinaHasan** [comment]
Thanks Will

When I tried to edit ~/.bashrc it refused any changes:

 It returns this error                                                                                                 
"~/.bashrc"
"~/.bashrc" E667: Fsync failed
Press ENTER or type command to continue

**Comment by willfurnass** [comment]
@madinaHasan As discussed in person, this is most likely due to your quota for /home/USERNAME being entirely exhausted.

**Comment by madinaHasan** [comment]
Thanks, I deleted some folders and now it works. At least I have tensorflow 1.4 successfully installed.

But I got the following error when I tried to run the script:
(tensorflow) [ac4mhx@sharc-node003 seq]$ module load libs/cudnn/6.0/binary-cuda-8.0.44
(tensorflow) [ac4mhx@sharc-node003 seq]$ module load apps/python/anaconda3-4.2.0
Conda uses environments to load different sets of Python packages
type conda env list to see the environments availible.
(tensorflow) [ac4mhx@sharc-node003 seq]$ source activate tensorflow
(tensorflow) [ac4mhx@sharc-node003 seq]$ python train.py 
Traceback (most recent call last):
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 2, in <module>
    from model.ner_model import NERModel
  File "/shared/machine_hearing1/Shared/tasks/stuttering/seq/model/ner_model.py", line 3, in <module>
    import tensorflow as tf
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/data/ac4mhx/.conda-sharc/tensorflow/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by twinkarma** [comment]
@madinaHasan The error you're getting is because you're using a GPU version of Tensorflow on a CPU node. Either use a gpu node (or the DGX-1 ) or check the [official tensorflow installation instructions ](https://www.tensorflow.org/install/install_linux) to find the correct CPU & Python version appropriate for you.

**Comment by twinkarma** [comment]
From Sadeen:

> I moved to ShARC and I tryed to follow the instructions you post but I couldn't load conda 
> 
> [acp15ssa@sharc-login1 stuttering]$ qrshx
> 
> [acp15ssa@sharc-node002 stuttering]$ module load libs/cudnn/6.0/binary-cuda-8.0.44
> 
> init.c(556):ERROR:161: Cannot initialize TCL

**Comment by twinkarma** [comment]
Sadeen can you check a few things for me?:
* In your .bashrc or .bash_profile do you have any modules pre-loaded?
* Do you already use conda environment from Iceberg?

**Comment by Sadeen** [comment]
Hi, 

Thank you Twin. 

In your .bashrc or .bash_profile do you have any modules pre-loaded? No 
Do you already use conda environment from Iceberg? yes its work on iceberg

**Comment by madinaHasan** [comment]
@twinkarma Thanks Twin, I used this installation command and it works now:

pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.4.0-cp35-cp35m-linux_x86_64.whl

**Comment by twinkarma** [comment]
@madinaHasan That's great, glad it works!

**Comment by twinkarma** [comment]
Update on Sadeen's issue. The .bashrc file has LD_LIBRARY_PATH directly to a conda environment's library folder and this causes conflict with ShARC's TCL (as conda for some reason has its own TCL library).
