### ISSUE TITLE
Limiting number of concurrent jobs

### ISSUE THREAD

**Issue by twinkarma** [RSE-Sheffield/GPUComputing#11]
From Yunita:

I have an array of parallel jobs which I created using -t option. 
I'm about to submit to rse queue but I'm afraid it will occupy all the gpu slots. 
Do you know how to limit the number of parallel jobs to run? I don't mind if some jobs wait in a queue.

**Comment by twinkarma** [comment]
You can use the -tc flag to specify the maximum number of concurrent jobs e.g. for 5 concurrent jobs

qsub -t 1-100 -tc 5 my_job_array_script.sh

or as part of your submission script:

```
#$ -t 1-100
#$ -tc 5

```

@willfurnass  Would it be worth adding this to the documentation?

**Comment by willfurnass** [comment]
Users aren't encouraged to impose their own limits on the number of concurrent tasks for CPU-only job arrays but this might be needed for GPU job arrays given that Grid Engine's resource accounting and the associated fair share mechanisms don't account for GPU usage.   I'll discuss with @anthonybrookfield

**Comment by willfurnass** [comment]
I think it's best for now if people do specify limits on # concurrent tasks when submitting GPU array jobs, particularly if those are to run on the DGX1.  Yes, adding something to the docs would be a good idea.

**Comment by twinkarma** [comment]
Amended job array page in PR rcgsheffield/sheffield_hpc#773
