### ISSUE TITLE
Error with tensorflow 

### ISSUE THREAD

**Issue by Heipiao** [RSE-Sheffield/GPUComputing#5]
Hi, 

I am using tensorflow with singularity, but when i use gpu, it can't find any gpu
![capture](https://user-images.githubusercontent.com/9475632/28466846-a86f66e6-6e25-11e7-9275-b2b1eae8f63d.PNG)
but when I  use command nvidia-smi, i can find all GPUS
![capture1](https://user-images.githubusercontent.com/9475632/28466927-e927820e-6e25-11e7-851d-4a01b66ec2de.PNG)
So I transfer my work to a virtual envorioment in my Home dir, but it takes a new issue about CUDA, I had try both 

- module load libs/cudnn/5.1/binary-cuda-8.0.44
- module load libs/cudnn/5.1/binary-cuda-7.5.18
None of them helps.

There are a related talk in google Gropu,[https://mail.google.com/mail/u/1/#inbox/15d52f5be122f3fe](https://mail.google.com/mail/u/1/#inbox/15d52f5be122f3fe)
and some advice from [stackoverflow](https://stackoverflow.com/questions/38303974/tensorflow-running-error-with-cublas)

thanks a lot

**Comment by Heipiao** [comment]
There is sreen shot of cuda error:
![capture2](https://user-images.githubusercontent.com/9475632/28467122-c2f6c47c-6e26-11e7-93af-1864ab5f9a03.PNG)

**Comment by willfurnass** [comment]
@Heipiao I upgraded the NVIDIA driver on the DGX-1 (node126 in ShARC) from 375.39 to 376.66 today; this *may* be related.

**Comment by willfurnass** [comment]
@Heipiao Can you try again?  I've ensured that the latest NVIDIA driver is installed in a place where Singularity can find it.

**Comment by Heipiao** [comment]
It works,thank you very much!

**Comment by willfurnass** [comment]
Great!

**Comment by Heipiao** [comment]
I meet a new problem since today, tensorflow can not find GPU. when I use command nvidia-smi, I can't get any output. I had meet such before. there is a discuss about that in HPC [`google group`](https://groups.google.com/a/sheffield.ac.uk/forum/?hl=en-GB#!topic/hpc/TGBS1V8jnSU)

**Comment by willfurnass** [comment]
None of the GPUs can be accessed; I think there is a problem with the NVIDIA driver and the node needs rebooting.  I can't do that just now as someone is running a GPU-only job on it (see `qstat -u \* -q rse.q@sharc-node126 -t -s r`)

**Comment by Heipiao** [comment]
I think ,no job running node126 now. he quit it, please reboot it.

**Comment by willfurnass** [comment]
@Heipiao - someone's still running a job on the machine.

**Comment by Heipiao** [comment]
We can do nothing but wait

**Comment by willfurnass** [comment]
@Heipiao The node's been rebooted; try again.
