### ISSUE TITLE
ShARC: Installing custom python packages inside singularity images with conda

### ISSUE THREAD

**Issue by twinkarma** [RSE-Sheffield/GPUComputing#6]
Query refers to the Singularity image at `/usr/local/packages/singularity/images/python-dl/gpu.img`

>  I have tried the singularity image, and I was able to import both Pytorch and Tensorflow successfully.
> However, I do need to install additional python libraries for my experiments. What would you recommend as the best way to do this ? Can I download or recreate your singularity image(s) locally on my machine, install the needed libraries, and then upload again in order to run it, or is there another way to do this ?

**Yes you can download the image to your local machine and install the packages as root**

The actual image is in /usr/local/packages/singularity/images/python-dl/tf1.3.0-t0.9.0-pyt0.2.0-cudnn6.0-ubuntu16.04.img

```
# After downloading the image to your desktop and open the image with write access like so
sudo singularity shell -w imagename.img

#Then you can just use pip install or conda install to install any custom packages you want. e.g.
conda install numpy

```
You can then upload the image back to your `/home` or `/data` afterwards and run it as any other image e.g.

```
#To use interactively
singularity shell /home/yourusename/mymodifiedimage.img

#To use in a job script
singularity exec /home/yourusename/mymodifiedimage.img python myscript.py
```

**Comment by twinkarma** [comment]
Note that conda's `source activate` doesn't work well with `singularity exec` as it defaults to using `/bin/sh` and hence packages installed in a virtual environment will not work well in a SGE job script.

**Comment by twinkarma** [comment]
> 
> I have tried this. However I get the following message when I tried running the command: 'sudo singularity shell -w tf1.3.0-t0.9.0-pyt0.2.0-cudnn6.0-ubuntu16.04.img'
> 
> ERROR  : Home directory is not owned by calling user: /root
> ABORT  : Retval = 255
> 
> I am able to call the command without 'sudo', but I am not able to make changes or install packages into the image.
> 
> Do you have an idea what might be the problem ?

@obabiola I'm looking in to it now.

**Comment by twinkarma** [comment]
@obabiola I can't seem to replicate this error.. can you do `ls -l /` and check if the `/root` folder belongs to root?

**Comment by obabiola** [comment]
@twinkarma  I was able to fix it by running
 `sudo singularity shell --home / -w tf1.3.0-t0.9.0-pyt0.2.0-cudnn6.0-ubuntu16.04.img`
 Thank you
