### ISSUE TITLE
Torch error when using new version of OpenNMT

### ISSUE THREAD

**Issue by twinkarma** [RSE-Sheffield/GPUComputing#8]
Query from @carolscarton:

I am trying to use the latest version of OpenNMT and I am afraid I have a problem with the torch available at Sharc/DGX-1.

I tried to execute the following (using the same command that you sent me ages ago):

singularity exec /usr/local/packages/singularity/images/torch/gpu.img th preprocess.lua

But I am getting the following error: 

/usr/local/torch/install/bin/luajit: /usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: /usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: /usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: /usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: /usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: module 'bit32' not found:No LuaRocks module found for bit32

	no field package.preload['bit32']

	no file '/home/twin/.luarocks/share/lua/5.1/bit32.lua'

	no file '/home/twin/.luarocks/share/lua/5.1/bit32/init.lua'

	no file '/usr/local/torch/install/share/lua/5.1/bit32.lua'

	no file '/usr/local/torch/install/share/lua/5.1/bit32/init.lua'

	no file '/usr/local/share/lua/5.1/bit32/init.lua'

	no file '/usr/local/share/lua/5.1/bit32.lua'

	no file '/usr/local/torch/install/share/luajit-2.1.0-beta1/bit32.lua'

	no file './bit32.lua'

	no file '/home/ac1ces/.luarocks/share/lua/5.1/bit32.lua'

	no file '/home/ac1ces/.luarocks/share/lua/5.1/bit32/init.lua'

	no file '/home/twin/.luarocks/lib/lua/5.1/bit32.so'

	no file '/usr/local/torch/install/lib/lua/5.1/bit32.so'

	no file '/usr/local/torch/install/lib/bit32.so'

	no file '/usr/local/lib/lua/5.1/loadall.so'

	no file '/usr/local/lib/lua/5.1/bit32.so'

	no file './bit32.so'

	no file '/home/ac1ces/.luarocks/lib/lua/5.1/bit32.so'

stack traceback:

	[C]: in function 'error'

	/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'

	preprocess.lua:1: in main chunk

	[C]: in function 'dofile'

	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk

	[C]: at 0x00405d50

Apparently there is a library (?) missing. The old version that I was using before does not show the same error (might be something new?)

**Comment by twinkarma** [comment]
@carolscarton If I remember correctly I've actually had to build and install opennmt in to the image itself. How are you actually using the new version?

**Comment by carolscarton** [comment]
Hi Twin, I have cloned from their github following exactly what is on their webpage: http://opennmt.net/OpenNMT-py/installation/

**Comment by twinkarma** [comment]
The version you're using is designed for `PyTorch` which is different from `Torch` that's been installed in the image that you're using. `PyTorch` takes the concept from `Torch` but is recoded completely using Python so they are not compatible with each other. 

If you would like to use `PyTorch` and `OpenNMT-py`, I'd recommend using Anaconda (http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/python.html) to create a virtual python environment and installing these python packages to your local directory.

**Comment by carolscarton** [comment]
Sorry Twin, I meant this link: http://opennmt.net/OpenNMT/installation/ (the torch version and not the pytorch version)

**Comment by twinkarma** [comment]
Ah ok looks like it's just missing a library. I'll add it on now.

**Comment by twinkarma** [comment]
@carolscarton I've updated the image now with the missing library. Can you test to see if it works?

**Comment by carolscarton** [comment]
@twinkarma Yes! It passed from that stage where the error was on the bit32 library. However, now I have a new problem:

When I use the following command:

singularity exec /usr/local/packages/singularity/images/torch/gpu.img th preprocess.lua

I get the following error: /usr/local/torch/install/bin/luajit: /usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: module 'tds' not found:No LuaRocks module found for tds


If I try with another singularity package, I get a different error:

singularity exec /usr/local/packages/singularity/images/torch/v7-TESTING.0.2.img th preprocess.lua

/usr/local/torch/install/bin/luajit: preprocess.lua:39: attempt to index field 'HookManager' (a nil value)

**Comment by twinkarma** [comment]
@carolscarton Strange, I thought tds has already been installed. I'm not in the office today so I'll have a look at it for you when I'm in tomorrow.

**Comment by twinkarma** [comment]
@carolscarton It's installed now. Do you want to give it another try?

**Comment by carolscarton** [comment]
@twinkarma preprocess.lua seems to be working! :) 

I am experimenting with train.lua now, and it also seems to be working fine.

Many thanks!

**Comment by twinkarma** [comment]
@carolscarton Great, I'll leave this issue open for a couple of days just in case. If you encounter any other problems, post it here.

**Comment by carolscarton** [comment]
Hi @twinkarma, I was using the image fine until now that apparently all GPUs at Sharc are being used (or at least I can't get a node for some reason). I then, tried to use the same image at the DGX-1 node, but I got some errors. I was trying the translate.lua script:

/usr/local/torch/install/bin/luajit: /usr/local/torch/install/share/lua/5.1/nn/Linear.lua:66: cublas runtime error : library not initialized at /usr/local/torch/extra/cutorch/lib/THC/THCGeneral.c:387
stack traceback:
	[C]: in function 'addmm'
	/usr/local/torch/install/share/lua/5.1/nn/Linear.lua:66: in function 'func'
	/usr/local/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/usr/local/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'func'
	/usr/local/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/usr/local/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'updateOutput'
	./onmt/modules/Network.lua:16: in function 'func'
	/usr/local/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/usr/local/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	./onmt/modules/Encoder.lua:240: in function 'forward'
	./onmt/translate/Translator.lua:417: in function 'translateBatch'
	./onmt/translate/Translator.lua:614: in function 'translate'
	/data/ac1ces/OpenNMT/translate.lua:221: in function 'main'
	/data/ac1ces/OpenNMT/translate.lua:344: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

It does work fine in Sharc, since I have used many times. I though that both Sharc and DGX shared the same image, but it appears this is not the case?

**Comment by twinkarma** [comment]
Hi @carolscarton, this is a current issue where the update of the graphics driver has caused Singularity to not work for the GPU. I'm waiting for a new version of Singularity to be updated so that I can test and roll it out to everyone. 

You can track the progress of this at issue #7

**Comment by twinkarma** [comment]
This issue should have been resolved now along with the update to singularity 2.4. @carolscarton  Are you still having isues?

**Comment by carolscarton** [comment]
Hi Twin, sorry for taking so long to answer. The problem is that it is being impossible to use Sharc as the queues have been ridiculously long. The last time I tried to use it, a simple job requiring only 1 gpu took 1 week to start. 

Anyway, my answer to your question may be yes. Last time I used it, it worked...

**Comment by twinkarma** [comment]
@carolscarton The wait on the DGX is not normally that bad. Are you requesting a lot of GPUs or large amount of memory on your jobs?

**Comment by twinkarma** [comment]
Closed due to inactivity
